/***********************************************************************}
{                                                                       }
{  This file contains routines used to interface to FEFF 4.06           }
{                                                                       }
{  Copyright (C) Paul J. Ellis, University of Sydney, 1993.             }
{                                                                       }
{***********************************************************************/

#if !defined (__FEFF4_C)

#define __FEFF4_C

#include "feff4.h"

#include "console.h"


  /*********************************************************************}
  {                                                                     }
  {  Create a FEFF4 input file.                                         }
  {                                                                     }
  {*********************************************************************/

int make_FEFF4 (char name [], int edge, int shells, double Z [],

                double N [], double R [], double s [], double S02) {

  FILE * feff_inp;

  int shell;

  feff_inp = fopen ("feff.inp", "w");

  if (feff_inp == NULL) {

    cwarn (" make_FEFF4 (%s): can't open feff.inp\n", name);

    return 0;

    }

  fprintf (feff_inp, "FEFF 4 command file generated by %s\n\n", name);

  fprintf (feff_inp, "HOLE    %8d %9.5f\n", edge, S02);
  fprintf (feff_inp, "CONTROL        1%8d\n", shells);
  fprintf (feff_inp, "SHELL          0%8.0f\n", Z [0]);

  for (shell = 1; shell <= shells; shell++)

    fprintf (feff_inp, "SHELL   %8d %7.0f %9.5f %9.5f %9.5f       0\n",
                        shell, Z [shell], max (1.0, floor (N [shell] + 0.5)),
                        R [shell], s [shell]);

  fprintf (feff_inp, "OVERLAP        0\n");

  for (shell = 1; shell <= shells; shell++)

    fprintf (feff_inp, "%8d %7d %9.5f\n",
                        shell, (long) (max (1, N [shell] + 0.5)), R [shell]);

  for (shell = 1; shell <= shells; shell++)

    fprintf (feff_inp, "OVERLAP %8d\n       0       1 %9.5f\n",
                        shell, R [shell]);

  fclose (feff_inp);

  return 1;

  }


  /*********************************************************************}
  {                                                                     }
  {  Execute FEFF4.  The executable must be in the PATH or in the       }
  {  directory specified by FEFF_DIRECTORY.                             }
  {                                                                     }
  {*********************************************************************/

int execute_FEFF4 (char name []) {

  long i;

  char * d, path [256];

  fflush (stdout);

  path [0] = 0;

  d = getenv ("FEFF_DIRECTORY");

  if (d) {

    strcat (path, d);

#if defined (BS_SEPARATOR)

    strcat (path, "\\");

#else

    strcat (path, "/");

#endif


    }

  strcat (path, "FEFF4");

  i = system (path);

  return i == 0;

  }


#endif /* __FEFF4_C */
